### ISSUE TITLE
Expandable table row overlap table heading

### ISSUE THREAD

**Issue by ZeroX-DG** [moaijs/moai#109]
![bug](https://user-images.githubusercontent.com/12984316/112978495-e873aa80-91b3-11eb-9509-456358505eb9.gif)
![image](https://user-images.githubusercontent.com/12984316/112978681-21ac1a80-91b4-11eb-9204-eeabab48cc2e.png)

**Comment by thien-do** [comment]
oh shit sorry :(

**Comment by ZeroX-DG** [comment]
Fixed in the latest version of Moai.

**Comment by thien-do** [comment]
oh great thank you @ZeroX-DG !
