### ISSUE TITLE
Require code format on commit

### ISSUE THREAD

**Issue by thien-do** [moaijs/moai#115]
We use prettier to format our code and we do have a config at https://github.com/moaijs/moai/blob/main/prettier.config.js However, it's totally optional so far, as we can commit without having use it. (Thankfully, our contributors seem to use editors with proper code formatting built-in.)

We should now setup something to run prettier (or at least to check the format) on commit. Maybe use Husky or something similar.

**Comment by thien-do** [comment]
Thank you @lqt93 ! Please help me with this

**Comment by lqt93** [comment]
To use Prettier and Pre-commit hook together, there are some [options](https://prettier.io/docs/en/precommit.html)
I will choose to use first option which uses [lint-staged](https://github.com/okonet/lint-staged) in combination with [simple-git-hooks](https://github.com/toplenboren/simple-git-hooks) which is a lib to help managing git-hooks (lighter and simplier to config than husky)

**Comment by thien-do** [comment]
Thank you @lqt93 ! Your comment is great and I totally agree.

Just one thing, is it possible to have this as a check when a contributor creates a PR? Like if a committed file is not formatted, the PR merge should be blocked

**Comment by lqt93** [comment]
I know it is possible but at the moment, I still don't have a specific solution for that. Need to research more.

**Comment by ZeroX-DG** [comment]
I suggest using github action for CI (just because it's native to github), but feel free to use other services such as travisCI. After that we can setup a status check before merging rule for the master branch. This way the tests & formatting jobs will be run on the CI. The PR can only be merged if the CI is passed.

https://docs.github.com/en/github/administering-a-repository/managing-a-branch-protection-rule

**Comment by thien-do** [comment]
I think we will go with GitHub actions :D The cost of bringing another CI service is just too much for this project :(

**Comment by lqt93** [comment]
husky updated to 6.0.0 and lint-staged abandoned simple-git-hooks: https://github.com/okonet/lint-staged/pull/960
so, back to use husky for setup git hooks.

**Comment by thien-do** [comment]
Ok I'll close this in light of @lqt93 's excellent #135 . However it's worth to note that we won't run or enforce code format on commit, but as a check of the PR. Also this check would scan the whole repo (which is still quite fast) instead of just staged files.

It's not as good as a commit hook on staged files, yes, but it significantly simplified our setup, which is some thing I value a lot. For our current and near-future codebase size, I think we're good
