### ISSUE TITLE
Use Eslint 

### ISSUE THREAD

**Issue by lqt93** [moaijs/moai#119]
Use Eslint inside moai for better code style.

**Comment by thien-do** [comment]
@lqt93 Can you consider https://github.com/xojs/xo? It looks pretty good in our case. It supports eslint + prettier + typescript and we won't need to add more dependencies manually (only remove prettier and add xojs)

**Comment by thien-do** [comment]
Nah, the project seems not getting enough maintenance

**Comment by thien-do** [comment]
Done! THank you @lqt93
