### ISSUE TITLE
Write README.md please

### ISSUE THREAD

**Issue by monodyle** [moaijs/moai#133]
Some references:

- [Ant Design README](https://github.com/ant-design/ant-design/blob/master/README.md)
- [Australian Government Design System README](https://github.com/govau/design-system-components/blob/master/README.md)
- [Baseweb README](https://github.com/uber/baseweb/blob/master/README.md)
- [Biings Design system README](https://github.com/Biings/biings-ds/blob/master/docs/README.md)
- [Blueprint README](https://github.com/palantir/blueprint/blob/develop/README.md)
- [Carbon Design System README](https://github.com/carbon-design-system/carbon/blob/main/README.md)
- [Elastic UI README](https://github.com/elastic/eui/blob/master/README.md)
- [Evergreen README](https://github.com/segmentio/evergreen/blob/master/README.md)
- [Fiori Fundamental README](https://github.com/SAP/fundamental-styles/blob/main/README.md)
- [Grommet README](https://github.com/grommet/grommet/blob/master/README.md)
- [Liferay Design README](https://github.com/liferay-design/liferay.design/blob/master/README.md)
- [Orbit readme](https://github.com/kiwicom/orbit/blob/master/readme.md)
- [Pajamas Design System README](https://gitlab.com/gitlab-org/gitlab-services/design.gitlab.com/-/blob/master/README.md)
- [Patternfly README](https://github.com/patternfly/patternfly-react/blob/master/README.md)
- [Polaris README](https://github.com/Shopify/polaris-react/blob/main/README.md)
- [Primer README](https://github.com/primer/components/blob/main/README.md)
- [Protocol README](https://github.com/mozilla/protocol/blob/main/README.md)
- [Rimble README](https://github.com/ConsenSysMesh/rimble-ui/blob/master/README.md)
- [Spectrum README](https://github.com/adobe/react-spectrum/blob/main/README.md)
- [Stack README](https://github.com/StackExchange/Stacks/blob/develop/README.md)
- [Vanilla Framework README](https://github.com/canonical-web-and-design/vanilla-framework/blob/master/README.md)
- [Workday Canvas README](https://github.com/Workday/canvas-kit/blob/master/README.md)
- [Yoga README](https://github.com/Gympass/yoga/blob/master/README.md)

**Comment by thien-do** [comment]
ok :sosad:

**Comment by huytd** [comment]
a README is like a marketing material, there should be no rush, no push
