### ISSUE TITLE
Warning from ESLint and Prettier should be Errors

### ISSUE THREAD

**Issue by thien-do** [moaijs/moai#139]
In principle, we should prefer strictness. I see no reason having tens of warnings in the build. Either it's an error and must be fixed, or eles it's expected and should be noted properly (e.g. eslint disable)

**Comment by thien-do** [comment]
@lqt93 @ng-hai any of you know how to do this? I really don't want to list all the rules and manually set them to "error" in eslintrc... I'd like something like a simple config or option or even a pipe action for eslint and prettier

**Comment by ZeroX-DG** [comment]
@thien-do maybe this will help? https://github.com/moaijs/moai/pull/141
