### ISSUE TITLE
Component interface should be based (extend) on default HTML element attributes

### ISSUE THREAD

**Issue by monodyle** [moaijs/moai#160]
Look like Moai did support all props of HTMLElement, especially the control components like "Input".

I was created issue #159 about an hour ago, then I read core of Moai and realize that Moai is initial all attributes from step by step. It's an incrementally support, but sometimes we should using what browser did good.

So I have an idea that using `omit` or something else to support native HTML element attributes.

I have some references:

- https://github.com/ant-design/ant-design/blob/master/components/input/Input.tsx#L18-L19
- https://github.com/palantir/blueprint/blob/develop/packages/core/src/components/forms/controls.tsx#L31

**Comment by thien-do** [comment]
The references are really helpful! Thank you
