### ISSUE TITLE
Toast is not open for extension

### ISSUE THREAD

**Issue by violeine** [moaijs/moai#171]
Open interface for user to intercept with its own style

**Comment by thien-do** [comment]
Thanks @violeine .

This should be done around here: https://github.com/moaijs/moai/blob/1bbba39b15d42ca757b8deae758a3126286a9418/core/src/toast/pane/pane.tsx#L45

So the thing is Toast (ToastPane, to be exact) uses its styling (pane.module.css) directly (in the render function). This does not allow any extension.

What should be done is to have the middle layer (like ToastPane.styles.normal) so it works as an interface for others to modify safely.
