### ISSUE TITLE
Default color for Tag

### ISSUE THREAD

**Issue by lqt93** [moaijs/moai#197]
- Reason:
To make Tag easier to use, a default color is necessary. For example, in case users just want to use Tag for categorizing things or labeling and they don't know exactly what color to use. In that case, if Tag has a default color that is consistent with other components in Moai (e.g: Button), it would reduce the effort for users to choose a color. Besides, less prop for using a component is better.
- Solution:
  1. Create a default value for `color` prop which is Tags.color.gray.
  2. Create additional document for supporting it.

**Comment by thien-do** [comment]
Sorry @lqt93 but I don't think we will have this in the near future. It's just not convincible enough for me that "gray" tag is more common than other colors
