### ISSUE TITLE
Add badges to README.md

### ISSUE THREAD

**Issue by lqt93** [moaijs/moai#236]
As discussion in last issue that related to README.md, we should add some badges like: webuild, madeinvietnam, or any badge that is good for introducing and marketing MoaiJS.

**Comment by thien-do** [comment]
Some badges I'd like to have:
- Latest version of @moai/core in npm `@moai/core: 1.1.0`
- One out of webuild/madeinvietnam/byvietnamese or something. I'm still not sure about this

**Comment by thien-do** [comment]
Done
