### ISSUE TITLE
Expose category colors as an array

### ISSUE THREAD

**Issue by thien-do** [moaijs/moai#284]
Also it should be `as const`

**Comment by clitetailor** [comment]
Can give more description about the purpose of this issue. What does it do and how does it shall be?

**Comment by thien-do** [comment]
Hi @clitetailor category colors are currently exported as an object:

https://github.com/moaijs/moai/blob/c7ef4b5ce7a8f4dc160f45979e8b228bfa3cc4cc/core/src/category/category.tsx#L5-L14

We need to also export category colors as an array. It can be an array of values or keys
