### ISSUE TITLE
Tag should have small size

### ISSUE THREAD

**Issue by thien-do** [moaijs/moai#92]
We should touch:
- [tag.tsx](https://github.com/moaijs/moai/blob/main/core/src/tag/tag.tsx) to add the sizing stuffs
- [tag.module.css](https://github.com/moaijs/moai/blob/main/core/src/tag/tag.module.css) to add the necessary CSS
- [button.tsx](https://github.com/moaijs/moai/blob/main/core/src/button/button.tsx) and [input.tsx](https://github.com/moaijs/moai/blob/main/core/src/input/input.tsx) for reference on how to have sizing prop

**Comment by tuhuynh27** [comment]
@thien-do I wonder how the API should look like:

```javascript
<Tabs small>
```

or:

```javascript
<Tabs size="small">
```

or:

```javascript
<Tabs size={10}>
```

**Comment by thien-do** [comment]
@monodyle

**Comment by thien-do** [comment]
Sorry @monodyle :( as discussed, this was an invalid request
